### ISSUE TITLE
FBI stops installing when installing multiple cias

### ISSUE THREAD

**Issue by Ante0** [Steveice10/FBI#60] opened 2016-04-15 21:05 UTC
Let's say I want to install 3 different cias, FBI stops installing after the first cia is installed. It displays (for example) 5mb/5mb installed. 1/3 installed. And just stays like that until I press B. And larger files (800 mb is the biggest I've tried so far in fbi2) just freezes at a random point or gives a black screen and freezes (top screen still displays FBI though). Would having the H&S inject and the cia version installed at the same time give any conflicts?

**Comment by Steveice10** [comment] 2016-04-16 02:09
Cannot reproduce. Is this happening when you're running the injected or CIA version, and what are you using to send the CIA files to FBI?

**Comment by Ante0** [comment] 2016-04-16 09:09
It happens with the CIA version. I had the H&S version when I submitted this bug, but has since removed it, but the problem remains. 
I even reinstalled FBI 2.0.4. I transfer directly to my sdcard using computer.
I could now install a 1.7gb cia so that was probably just a rare bug. But the Multiple install still stops after the first cia is installed. Video of it, though it probably won't help at all :/
https://www.youtube.com/watch?v=iPNWkkilT-Y

**Comment by Steveice10** [comment] 2016-04-16 09:18
What are you using to send CIA files to FBI?

**Comment by Ante0** [comment] 2016-04-16 09:26
I just copy from computer to sdcard, by plugging in my sdcard in my computer. IF I do send I use some kind of ftppony fork, FTP-3ds 1.1. And filezilla on my computer. But for these I did not use network install, just directory install from sdcard.

**Comment by Steveice10** [comment] 2016-04-16 09:27
Ahhh, I thought this was network install. I'll look at the issue again in the morning. (2:27PM for me right now)

**Comment by Shinigati** [comment] 2016-04-16 11:18
This has also happened to me before as well. If i install like 10 cia's it might get up to 7/10 and say cia install failed but this was on 1.4.17 when i noticed it, i'm not sure if it still happens on the latest version.

**Comment by Steveice10** [comment] 2016-04-16 17:36
Should be fixed in latest source.

**Closed by Steveice10** 2016-04-16 17:36 UTC
