### ISSUE TITLE
FBI has some issues loading titles from the TWL

### ISSUE THREAD

**Issue by v0idst4r** [Steveice10/FBI#164] opened 2016-07-26 05:31 UTC
Hello I've been using FBI to load some TWL titles but to get them to load I have to go back to the main menu and exit before it loads. When I select the title and press launch I get error "Failed to launch title. Result code: 0xC8A0CC04 Level: Status (25) Summary: Invalid state (5) Module: Applet (51) Desc: <unknown> (4)"

**Comment by v0idst4r** [comment] 2016-07-26 05:33
Maybe you could have FBI auto exit after loading a TWL title?

**Comment by v0idst4r** [comment] 2016-07-26 16:43
What's strange is I woke up today and started using my 3DS then loaded a TWL title from FBI and it worked fine without an error

**Comment by v0idst4r** [comment] 2016-07-26 16:43
Might be my console I'll close if someone thinks the issue is unnecessary

**Comment by Steveice10** [comment] 2016-07-31 20:43
Cannot reproduce. Since it seems you aren't having this issue any more either, I'll go ahead and close this.

**Closed by Steveice10** 2016-07-31 20:43 UTC

**Comment by Eddyv99** [comment] 2017-10-24 00:57
I'm having this issue but running the game from a cartridge
