### ISSUE TITLE
FBI 2.0.x freezing

### ISSUE THREAD

**Issue by Mori-S** [Steveice10/FBI#59] opened 2016-04-14 18:24 UTC
I'm not sure if this is related to loading titles, but it seems to do it when I enter the menu sometimes. Thankfully it's never done it while I was removing something. Anyway if this is already known I apologize

**Comment by Steveice10** [comment] 2016-04-14 18:27
That's... very vague. Do you have any more specific details on how to reproduce this?

**Comment by Mori-S** [comment] 2016-04-14 18:28
I wish I did. I'll try messing around with it more to see if I can. If not you can just close it

**Comment by Mori-S** [comment] 2016-04-14 18:37
Oh I did figure out something else. Open a game, press home, launch FBI, tell it to close the app then it will load up with a black screen.

**Comment by Steveice10** [comment] 2016-04-14 18:42
Cannot reproduce that either.

**Comment by Mori-S** [comment] 2016-04-14 18:43
I'll make a video of it

**Comment by Steveice10** [comment] 2016-04-14 19:06
That might be due to it being injected into H&S.

**Comment by Mori-S** [comment] 2016-04-14 19:14
Oh no wonder. I didn't get a chance to test it with the cia version either. Once the h&s injection was fixed I removed it

**Comment by aliaspider** [comment] 2016-04-14 21:58
I can also reproduce this, it isn't exactly a freeze, but it takes too long (about 2 minutes) sometimes to display the filename of a certain file on my SD, and pressing back while it is in this state will cause the clock to stop, giving the impression that it hanged.
I still can't figure out what is special about that file (size 104320608 bytes), I tried renaming and copying again to the SD card but it still froze, copying only the first 10MB of the file didn't cause a freeze though.

**Comment by Steveice10** [comment] 2016-04-14 22:12
@aliaspider That issue is now fixed.

**Comment by Mori-S** [comment] 2016-04-14 23:11
Lol, i'm a terrible tester. Thanks for figuring out the actual problem

**Closed** 2016-04-15 00:38 UTC
