### ISSUE TITLE
Random freezes while deleting titles

### ISSUE THREAD

**Issue by akirayuki** [Steveice10/FBI#69] opened 2016-04-21 09:45 UTC
I am deleting some titles(because of Regionchange) using the latest version of FBI and I have some random freezes. I had to hold the power button for a couple of seconds to turn it off. My console is N3ds using Aureinand with a9lh.

One more issue:
I tried installing multiple CIAs(15 I guess) and everytime I go to my folder with the CIAs, it always freeze.
I'll be trying the latest source when I get back to my place.

**Comment by Ryuzaki-MrL** [comment] 2016-04-21 16:08
I can confirm this. It rarely happens, but it's quite annoying when it does.

**Comment by Steveice10** [comment] 2016-04-22 04:23
I've been making quite a few fixes here and there since the last release, so if someone could test this build of the latest source, that'd be great.

https://www.dropbox.com/s/866yhujdg859mor/FBI.zip?dl=0

**Comment by Steveice10** [comment] 2016-04-23 19:37
Closing, assumed fixed.

**Closed by Steveice10** 2016-04-23 19:37 UTC
