### ISSUE TITLE
freeze after accidently closing the 3ds 

### ISSUE THREAD

**Issue by yuukiw** [Steveice10/FBI#90] opened 2016-05-01 09:45 UTC
freeze after accidently closing the 3ds while installing a cia

**Comment by Steveice10** [comment] 2016-05-01 16:23
Are you on v2.2.1?

**Comment by Steveice10** [comment] 2016-05-02 02:27
Going to go ahead and close this, as this should be fixed with the latest releases and I can't reproduce it myself.

**Closed by Steveice10** 2016-05-02 02:27 UTC
