### ISSUE TITLE
DLC Issues

### ISSUE THREAD

**Issue by Zetchzie** [Steveice10/FBI#30] opened 2016-01-16 06:49 UTC
Ok so when installing dlc for Smash or Senran Kagura 2 it may also apply to other dlc, the game does not detect dlc unless installed with bigbluemenu.

**Comment by urherenow** [comment] 2016-01-16 07:01
Seconded. But I'm pretty sure I've brought this up several times before. It should be known already.

**Comment by Zetchzie** [comment] 2016-01-16 07:55
it works fine with Moon Chronicles and IronFall from what ive tested

**Comment by dogtopus** [comment] 2016-02-19 07:34
I can reproduce this issue with Home Menu DLC (aka themes)
Themes are not displayed in the theme menu unless installed with BBM

**Comment by Steveice10** [comment] 2016-04-13 01:07
Can someone with this issue test if it still happens with the latest source?

**Comment by dogtopus** [comment] 2016-04-13 01:45
@Steveice10 At leasr with Home Menu, deleting old DLC ticket and install DLC pack again works for me.

**Comment by Steveice10** [comment] 2016-04-13 01:50
Yeah, in one of the latest commits I made it so a title's existing installed version and ticket are deleted before installation, so I was wondering if that fixed installing DLC without any extra work.

**Comment by dogtopus** [comment] 2016-04-13 01:56
I don't like this behavior very much since if you previously downloaded a game from eShop, and later installed a cia version of the same game, your purchase record will gone :(
Same with legit DLCs vs custom/*cough* pirated *cough* DLCs

**Comment by Steveice10** [comment] 2016-04-13 01:57
It doesn't delete your purchase record, only the local ticket on the system, which AFAIK can be redownloaded in the eShop. Plus, why install a CIA for a game you can download from the eShop? :P

**Comment by dogtopus** [comment] 2016-04-13 02:13
Oh really? I always thought they are only being stored locally...
BTW The installed DLCs are working normally without clearing the tickets manually before installation.

**Comment by Steveice10** [comment] 2016-04-13 02:14
Cool, thanks for testing. Will close then, since this is fixed in source.

**Closed by Steveice10** 2016-04-13 02:14 UTC
