### ISSUE TITLE
Using latest version with slowhax implemented, but can't install legit CIAs on 11.1.0-34U?

### ISSUE THREAD

**Issue by Alerdy** [Steveice10/FBI#247] opened 2016-12-26 15:55 UTC
Using the latest build of FBI, with waithax implemented, it won't let me install legit CIAs on my 11.1.0-34U New 3DS. When I select the CIA, I get the option to move, copy, rename, etc. However, it has no option to install the CIA. I also don't seem to have internet access, even though wireless is on and I am connected to wifi through System Settings.

**Comment by Steveice10** [comment] 2016-12-26 18:52
Is waithax successfully completing according to the console output when FBI starts up?

**Comment by Sharanbasav** [comment] 2016-12-27 05:49
Same issue for me. It gets annoying af , i downloaded a legit CIA of Pokemon moon and it didn't show any option to install anything. Please fix this I wasted so much time downloading the CIA Pls Pls PLSSSS

**Comment by Sharanbasav** [comment] 2016-12-27 08:15
I've done everything; I put the CIA on the root of the SD card,it said success when FBI opened, BUT IT STILL WONT GIVE ME THE OPTION TO INSTALL THE CIA. PLS DO SOMETHING

**Comment by Sharanbasav** [comment] 2016-12-27 08:22
Oh and also, every time I open FBI, it always goes through the process of waithax every time, so it takes an hour just to open FBI. Is this normal, or is my 2ds weird?

**Comment by Steveice10** [comment] 2016-12-27 09:04
The wait is normal, and can't really be avoided. As for your issue, can you describe the information it shows on the top screen when the CIA file is selected in the file browser? Would help to narrow down exactly where it's failing to identify it as a CIA file.

**Comment by Sharanbasav** [comment] 2016-12-27 09:11
It gives the CIA name, and then it says File type: Archive. I extracted it and everything, but it still doesn't have any effect

**Comment by Sharanbasav** [comment] 2016-12-27 09:14
I mean, i extracted it from the zip

**Comment by Steveice10** [comment] 2016-12-27 18:05
What about the file size? Does it show that?

**Comment by Sharanbasav** [comment] 2016-12-27 18:12
Yes the file size is 2.98 GB. It shows it clearly at the top

**Comment by Steveice10** [comment] 2016-12-27 18:19
And lastly, the file name definitely ends in ".cia"?

**Comment by Sharanbasav** [comment] 2016-12-27 18:50
Yes

**Comment by Steveice10** [comment] 2016-12-27 19:00
Make sure to try the build I edited in the link to, then.

**Comment by Sharanbasav** [comment] 2016-12-27 19:02
Ok. Thanks for taking the time to help me man

**Comment by Sharanbasav** [comment] 2016-12-27 20:08
Nope. It didn't work. As soon as I press SD, it comes up with a message saying:
Error 
Failed to get information of CIA file.
Result code:0x00000000
Level: Success (0)
Summary : Success (0)
Module : Common (0)
Desc: Success (0)

WHAT SHOULD I DO

**Comment by Steveice10** [comment] 2016-12-27 21:30
...shoot. My bad on the error reporting showing success, try this. Note that I don't expect this to fix the problem, I just need to know what the error is so I can look into it.

https://www.dropbox.com/s/5ok1bazbzqsvlcj/FBI.zip?dl=1

**Comment by Sharanbasav** [comment] 2016-12-28 03:35
Ok. And nedwill finally released soundhax and fasthax

**Comment by Sharanbasav** [comment] 2016-12-28 03:36
I mean,not yet, but in a couple of hours he will!

**Comment by Sharanbasav** [comment] 2016-12-28 06:13
As you expected ,it failed when is clicked on SD. Here is the error code:

Error
Failed to install CIA file
Result code:0xD8E007F7
Level: Permanent (27)
Summary: Invalid argument (7)
Module: Kernel (1)
Desc: Invalid handle (1015)

**Comment by Steveice10** [comment] 2016-12-28 07:10
It seems AM isn't initializing properly. Does this fix the issue?

https://www.dropbox.com/s/vmovm6dhrknai5z/FBI.zip?dl=1

**Comment by Sharanbasav** [comment] 2016-12-28 07:21
I'll try

**Comment by Sharanbasav** [comment] 2016-12-28 10:07
Nope. This time it gave me the option to install the CIA, but is said 'failed to install CIA ' and gave a bunch of errors after installing it.

**Comment by Steveice10** [comment] 2016-12-28 16:33
What error did it fail to install with, and what errors came afterwards?

**Comment by Sharanbasav** [comment] 2016-12-28 16:35
Gimme an hour or two, I'll try again and tell you

**Comment by Sharanbasav** [comment] 2016-12-28 19:03
Here's what it says after it fails.

Error
Failed to install CIA file
Result code:0xD8E0806A
Level: Permanent (27)
Summary: Invalid argument (7)
Module:AM(32)
Desc: Cert signature or hash check failed

**Comment by Steveice10** [comment] 2016-12-29 02:26
Your CIA doesn't seem to actually be legit, then.

**Comment by Sharanbasav** [comment] 2016-12-29 02:46
The CIA is legit, the version number , title Id and everything match the legit cias

**Comment by urherenow** [comment] 2016-12-29 02:50
That's not what makes it legit. The TICKET does.

**Comment by Sharanbasav** [comment] 2016-12-29 02:50
Where can I see the ticket then

**Comment by Sharanbasav** [comment] 2016-12-29 02:55
Besides, at the place where I downloaded it from, everyone was saying thank you for posting a legit cia and whatnot

**Comment by Steveice10** [comment] 2016-12-29 03:26
Well as far as the AM service is concerned, it doesn't seem to be a valid signature. Try another legit CIA, maybe?

**Comment by Sharanbasav** [comment] 2016-12-29 03:28
Do I need to have a folder for seed.dat files on my SD card? If I do then that was my bad, i dont have any

**Comment by Steveice10** [comment] 2016-12-29 16:46
I don't think seeds affect this stage of the installation process. Like I said, I would recommend trying something else legit, as if that succeeds, then the issue was you simply were using a non-legit CIA.

**Comment by Bog0th** [comment] 2016-12-29 21:25
hi, i tried to use fbi on 11.0.0-33E, my entrypoint to launch hbl is soundhax.
i got the same error as the one dude above:

Error
Failed to install CIA file
Result code:0xD8E007F7
Level: Permanent (27)
Summary: Invalid argument (7)
Module: Kernel (1)
Desc: Invalid handle (1015)

i tried it like 4 times with different tickets (which should REALLY be legit, confirmed via multiple sources) via sd card and via qr code scanning. i tried a ton of legit tickets (pretty much every bundle option).
the wifi-logo in the top is crossed, it seems like fbi can't access it (?) - unless in fbi, wifi is working w/o problems. 

for scientists sake i will try out the new version you posted above and will report back later :)

**Comment by hogofwar** [comment] 2016-12-29 22:50
Using the latest FBI release and soundhax I am also getting the Invalid handle (1015) error for most options in the menu. Like the original poster, no option to install the CIAs in the SD card is given. I will be trying the version posted in this thread and see if it helps.

**Comment by Steveice10** [comment] 2016-12-29 23:27
For the invalid handle error, use the latest build I linked to. It should already be fixed in source.

**Comment by Bog0th** [comment] 2016-12-29 23:30
alright, with your updated release fbi got wifi connection. but:

-when i browse through "tickets" in fbi i see a long list of green title ids with a few red ones. it only shows the title id on both screens, no idea if that's normal behaviour. i can 'install' and its downloading something, but know idea what and no too big files anyway. maybe system apps?
-when i try to install via qr it shows:

Error
Failed to install from URL.
Result code:0xD8E0806A
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)

even though the titlekey is confirmed being legit (at least multiple sources say so).
-when i try to install the tickets i put onto the sd card (again, confirmed legit, tried like every eu region game) it gives this error:

Error
Failed to populate ticket list.
Result code:0xC8804478.
Level: Status (25).
Summary: Not found (4).
Module: FS (17)
Desc: Doesn't exist / Failed to open (120)

think that's all for now, thanks for your great work dude! =)

**Comment by Steveice10** [comment] 2016-12-29 23:57
* The green tickets are in use (the title is installed), and the red ones are not. The title ID is supposed to be all that shows up, as tickets don't contain any more useful info than that. The files that download when you install from CDN are the actual title contents.
* What legit title is it, and have you tried a different title known to be legit to make sure?
* That's... interesting. I'll look into that error.

**Comment by Bog0th** [comment] 2016-12-30 00:28
alright, thanks for the quick response! still kinda new into this stuff :) so i'm always happy to learn.

i tried titles like mk7, super smash bros, monster hunter 4 ultimate, zelda: majoras mask and even region free titles like the pokemon blue/red/yellow titles -via tickets-.
via qr code i tried mk7 and one more i can't recall exactly, maybe smash bros.

**Comment by Steveice10** [comment] 2016-12-30 00:36
And was the third issue with a single ticket install or an installation of all tickets in a directory?

**Comment by Bog0th** [comment] 2016-12-30 00:48
i got them in a directory (browsed from sd to the ticket folder), but tried to install them one-per-one. same error code for every ticket. (~10 tried, some left).

**Comment by Steveice10** [comment] 2016-12-30 01:02
Alright. Unfortunately, I'm away and don't seem to have a way to get tickets on to my 3DS SD card right now, so I probably won't be able to test and figure the issue out until tomorrow.

**Comment by Burningocean2012** [comment] 2016-12-30 01:12
Just wanted to come by here to thank Steveice10 for the build in this topic they suggested.It fixed my issue that I have been worried about.My topic was closed so I decided to thank them here.

**Comment by hogofwar** [comment] 2016-12-30 01:23
I also want to confirm this fixed my issue.

**Comment by Sharanbasav** [comment] 2016-12-30 05:37
Man oh man, things are crazy. I downloaded another legit CIA of Pokemon moon( this time it's 100% confirmed legit) and now I get the following error
Result code:0xD8A08012 
Level: Permanent (27)
Summary :Invalid state (5)
Module : AM (32)
Desc:<unknown> (18)

**Comment by Steveice10** [comment] 2016-12-30 07:49
Check for it in the title and ticket lists and delete it if it's there. I believe that error is related to an incomplete installation.

**Comment by Sharanbasav** [comment] 2016-12-30 07:53
Ok. Thanks for your help Steve. I'm sorry for giving   
you all this trouble

**Comment by Sharanbasav** [comment] 2016-12-30 07:56
By the way there is no game icon for the CIA , and the region is unknown. Is this normal is something wrong with the CIA? At the place where I downloaded it from, the CIA has worked for EVERYONE except me. I wonder if it's my 2ds which has a problem

**Comment by Sharanbasav** [comment] 2016-12-30 08:41
I did everything u said, but it still doesn't work.

**Comment by Sharanbasav** [comment] 2016-12-30 09:58
Do u think this is happening because my 2ds is European

**Comment by Sharanbasav** [comment] 2016-12-30 20:01
Nope. I did everything u said but here's what error I get

Result code:0xD8A08012
Level: Permanent(27)
Summary: Invalid state(5)
Module: AM (32)
Desc: <unknown > (18)

I deleted it in the ticket section and everything, but it still comes up with this error. Pls do something

**Comment by Steveice10** [comment] 2016-12-30 23:06
From looking up instances of other people getting that error, it seems that your CIA file might be invalid, or at least that's what DevMenu would tell you. Perhaps your download messed up?

Anyway, I'm going to go ahead and close this since the original issue (no option to install/etc) is fixed. The other issue mentioned with installing tickets seems to also be fixed in the latest source.

**Closed by Steveice10** 2016-12-30 23:06 UTC

**Comment by Bog0th** [comment] 2016-12-31 14:22
hey! sorry for posting here again, but i can't find a way to write you a direct message on this site and i don't want to open a new request.
can you upload your latest source release as *.3dsx or tell me how to compile it? you we need devkitARM and citro3d to build, but i can't get it done myself without further explanation :(

**Comment by urherenow** [comment] 2016-12-31 15:03
Look for me on gbatemp and read the thread in my sig. It applies to all 3ds projects, and any additional requirements are usually listed in the readme.md on the project's github page.

**Comment by Bog0th** [comment] 2016-12-31 15:28
thanks!
