### ISSUE TITLE
Gui freezes and flashes in "Titles"

### ISSUE THREAD

**Issue by poutros** [Steveice10/FBI#353] opened 2017-07-03 16:07 UTC
I have checked all of the other options and only the "Titles" one has this issue. Whenever I select it, the gui randomly freezes after sometime and while it hasn't frozen, it continually flashes at random periods. It seems to have no pattern of when it freezes or flashes. It makes it impossible to do anything with installed titles unless someone is fast enough. Title installation seems fine though.

O3DS Luma 8.1 (it happened with 8.0 as well), 11.4.0-37E

It started to happen when I installed B9S.

**Comment by Steveice10** [comment] 2017-07-03 17:04
Duplicate of https://github.com/Steveice10/FBI/issues/352

**Closed by Steveice10** 2017-07-03 17:04 UTC
