### ISSUE TITLE
Freeze on folder open

### ISSUE THREAD

**Issue by CrashMan054** [Steveice10/FBI#66] opened 2016-04-18 14:53 UTC
If there are more than 8 CIAs in a single folder, or even on the root of the SD, the entire program freezes and requires a system reboot.

**Comment by BPSpike** [comment] 2016-04-18 19:18
Not sure if that's the trigger for the freezing. I know some cias like 0004008c00008f00 (home menu themes) does hang for a bit while getting the info, tho.
Did you try waiting longer than usual to see what would happen?

**Comment by CrashMan054** [comment] 2016-04-18 21:59
I left it alone for a solid 2 minutes, it did nothing. The cias inside were GBA VC games. I had some theme cias in a folder, but I managed to install them. The freeze only happens if I open the folder. But for some reason, FBI doesn't always let me install all cias in a folder (like these GBA games).

**Comment by Steveice10** [comment] 2016-04-19 01:59
Cannot reproduce. Any more details on what might be causing the issue? Because it isn't the amount of CIAs.

**Comment by CrashMan054** [comment] 2016-04-19 02:05
They're all GBA cias, maybe that could have something to do with it? I'm running 10.7 on an old3DS with arm9loaderhax and aureinand. Aurei is latest version, so is FBI. I've tried uninstalling and reinstalling FBI, no luck. I have no idea what else might be causing it.

**Comment by d0k3** [comment] 2016-04-21 09:54
Adding to this. Idk if mine is the same issue, but here I go:

FBI 2.0.5 seems to work fine with small stuff, but there is trouble with a folder of Riku converted big CIAs. The freeze happens at some time when extracting info from the CIAs. I can still move the cursor if I am fast enough after entering the folder. However, stay to long on one title -> freeze. The CIAs icon, name, author never turns up.

Maybe this is due to the SMDH still being encrpyted? Can't tell for sure. There are no problems whatsoever, with the same files, in FBI 1.4.17. You might also need to know that my SD card is a FAT32 / 64kB cluster formatted 64GB card.

**Comment by SXRWahrheit** [comment] 2016-04-21 16:06
I'm having this problem also. I am on FBI 2.0.5, FAT 32 / 64kb 128GB. I can generate a list of files in the dir or whatever if that would help, please let me know. My folder is a collection of VC/3DS CIAs.

**Comment by Steveice10** [comment] 2016-04-22 04:23
I've been making quite a few fixes here and there since the last release, so if someone could test this build of the latest source, that'd be great.

https://www.dropbox.com/s/866yhujdg859mor/FBI.zip?dl=0

**Comment by d0k3** [comment] 2016-04-22 12:24
I tried it, still crashes in the exact same way, no changes. If you have any other idea, I can try it. I will also try reducing the number of files in that folder, to see if it makes a difference.

**Comment by Steveice10** [comment] 2016-04-22 23:33
Here are two builds with:
* No CIA metadata: https://www.dropbox.com/s/f908ge9ksfs1ldg/FBI_nociaicon.zip?dl=1
* No CIA info at all: https://www.dropbox.com/s/pstrkwlvw2e3vj0/FBI_nociainfo.zip?dl=1

See if either of those don't have the freezing issue.

**Comment by Mori-S** [comment] 2016-04-22 23:43
I can't seem to get a freeze either with the old build. 32GB sd card with a 1.7 gb cia converted from a 3ds game installed pretty much fine. Usually i just stick one on the root of my sd card then erase it after installing it

**Comment by CrashMan054** [comment] 2016-04-23 02:48
Tried both builds, they have the exact same issue.

**Comment by Steveice10** [comment] 2016-04-23 03:02
@CrashMan054 Can you try this one, then? https://www.dropbox.com/s/nm1ceb7sig2lsn7/FBI_noopenfile.zip?dl=0

**Comment by imthe666st** [comment] 2016-04-23 23:27
Currently having the same issue, but with .tik files. FBI freezes on all builds. Including the build you just posted and version 2.1.0.  
Using a 128gb sd card on reinand emunand, latest fw. All tik files are valid.  
Something I noticed, normally it only shows me 9 tik files before freezing, but when there is another folder in the folder with the tik files, 10 files are shown.

**Comment by CrashMan054** [comment] 2016-04-23 23:57
That build froze instantly when opening the folder, instead of displaying a few titles first.

**Comment by Steveice10** [comment] 2016-04-24 21:04
Here's something else that might work, as it seemed to help in some testing I did:

https://www.dropbox.com/s/866yhujdg859mor/FBI.zip?dl=1

**Comment by d0k3** [comment] 2016-04-25 00:18
Tested it, looking good. No more crashes with the build Steve posted above.

**Comment by BPSpike** [comment] 2016-04-25 01:13
Same here, I have yet to find a crash while installing or loading folders with this build. Will report if I find one.

**Comment by Steveice10** [comment] 2016-04-25 02:09
Glad it seems to be fixed, closing.

**Closed by Steveice10** 2016-04-25 02:09 UTC
